[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
python-source = "python"
module-name = "dqasm.dqasm"

[project]
name = "dqasm"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "qiskit>=2.2.1",
]
